services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9563:9563"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PORT=8000
      - CORS_ORIGIN=http://localhost:80
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=490404
      - DB_NAME=issueTracker
      - ACCESS_TOKEN_SECRET=TANLFDLFDFSDLF
      - ACCESS_TOKEN_EXPIRY=1d
      - REFRESH_TOKEN_SECRET=KDFDLFDFLSD
      - REFRESH_TOKEN_EXPIRY=10d
      - EMAIL_USER=kaustubhjaitapkar2004@gmail.com
      - EMAIL_PASS=qhyb stys tllu ouku
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=490404
      - MYSQL_DATABASE=issueTracker
      - MYSQL_TCP_PORT=3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p490404"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local